config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :videos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/video.rb
class Video < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  require 'open-uri'
  require 'json'

  def index
    response = open('https://www.googleapis.com/youtube/v3/search?key=AIzaSyA1ViQVX1Q9dgNb8LBhynbeE17tLv07msc&channelId=UCtADbKzNiDJKRnCdddFxCIg&part=snippet,id&order=date&maxResults=50').read
    data_hash = JSON.parse(response)
    data_hash = data_hash['items']
    @videos = []
    data_hash.length.times { |i| @videos.push(data_hash[i]) }

  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ActionController::Base
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Asab</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="icon" data-bg="<%=image_path('logo.jpg') %>">

  </head>

  <body>
    <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    </body>
  </body>
</html>

app/views/partials/_navbar.html.erb
<nav id="menu">
  <ul class="links">
    <li><a><%= link_to 'Evim',root_path %></a></li>
    <li><a ><%= link_to 'Müziklerim' , videos_path%></a></li>
    <li><a href="../../../../../WebstormProjects/asab/elements.html">Elements</a></li>
    <li><a href="../../../../../WebstormProjects/asab/generic2.html">Elements</a></li>
    <li><a href="../../../../../WebstormProjects/asab/elements.html">Neobeat</a></li>

  </ul>
</nav>

app/views/partials/_page_header.html.erb
<!--
<header id="header" class="alt">
  <div class="logo"><img src="images/logo.jpg" height="56" width="56"> </div>
  <a href="#menu"><span>Menu</span></a>
</header>
-->

<!-- Image and text -->
<nav class="navbar navbar-light bg-faded" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="#">
    <img src="/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">
    Bootstrap
  </a>
</nav>

app/views/videos/index.html.erb
<!DOCTYPE HTML>
<!--
	Road Trip by TEMPLATED
	templated.co @templatedco
	Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
<html>
<head>
  <title>Açık Seçik Aşk Bandosu</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="stylesheet" href="assets/css/main.css" />
  <link rel="icon" href="images/logo.jpg">
</head>
<body class="subpage">

<!-- Header -->

<%= render partial: 'partials/page_header'%>

<!-- Nav -->
<nav id="menu">
  <ul class="links">
    <li><a href="index.html">Home</a></li>
    <li><a href="jacksroad.html">Açık Seçik Şeyler</a></li>
    <li><a href="elements.html">Elements</a></li>
    <li><a href="generic2.html">Elements</a></li>
    <li><a href="elements2.html">Neobeat</a></li>
  </ul>
</nav>

<!-- Content -->
<!--
  Note: To show a background image, set the "data-bg" attribute below
  to the full filename of your image. This is used in each section to set
  the background image.
-->

<section id="post" class="wrapper bg-img" data-bg="guitars.jpg">
  <div class="inner">
    <article class="box">
      <header>
        <h2>Some Quotes</h2>
        <p>05.09.1957</p>
      </header>
      <div class="content">
        <h2>Şarkılarımın Listesi</h2>
        <% @videos.each do |video| %>
            <img src="https://i1.ytimg.com/vi/<%=video["id"]["videoId"]%>/mqdefault.jpg" alt="<%=video["snippet"]["title"]%>" ><br>
            <a class="video-link" href="https://www.youtube.com/embed/<%=video["id"]["videoId"]%>" data-width="1920" data-height="1080"><%=video["snippet"]["title"]%></a><br><br>

      <% end %>
      </div>
      <footer>
        <ul class="actions">
          <li><a href="#" class="button alt icon fa-chevron-left"><span class="label">Previous</span></a></li>
          <li><a href="#" class="button alt icon fa-chevron-right"><span class="label">Next</span></a></li>
        </ul>
      </footer>
    </article>
  </div>
</section>

<!-- Footer -->
<footer id="footer">
  <div class="inner">

    <h2>Contact Me</h2>

    <form action="#" method="post">

      <div class="field half first">
        <label for="name">Name</label>
        <input name="name" id="name" type="text" placeholder="Name">
      </div>
      <div class="field half">
        <label for="email">Email</label>
        <input name="email" id="email" type="email" placeholder="Email">
      </div>
      <div class="field">
        <label for="message">Message</label>
        <textarea name="message" id="message" rows="6" placeholder="Message"></textarea>
      </div>
      <ul class="actions">
        <li><input value="Send Message" class="button alt" type="submit"></li>
      </ul>
    </form>

    <ul class="icons">
      <li><a href="#" class="icon round fa-twitter"><span class="label">Twitter</span></a></li>
      <li><a href="#" class="icon round fa-facebook"><span class="label">Facebook</span></a></li>
      <li><a href="#" class="icon round fa-instagram"><span class="label">Instagram</span></a></li>
    </ul>

    <div class="copyright">
      &copy; Untitled. Design: <a href="https://templated.co">TEMPLATED</a>. Images: <a href="https://unsplash.com">Unsplash</a>.
    </div>

  </div>
</footer>

<!-- Scripts
<script src="assets/js/jquery.min.js"></script>
<script src="assets/js/jquery.scrolly.min.js"></script>
<script src="assets/js/jquery.scrollex.min.js"></script>
<script src="assets/js/skel.min.js"></script>
<script src="assets/js/util.js"></script>
<script src="assets/js/main.js"></script>
<script src="assets/js/videopop.js"></script>
-->

<%= javascript_include_tag 'jquery.scrollex.min', 'data-turbolinks-track': 'reload' %>

<%= javascript_include_tag 'skel.min', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'util', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'main', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'jquery.scrolly.min', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'videopop', 'data-turbolinks-track': 'reload' %>

</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE HTML>
<!--
	Road Trip by TEMPLATED
	templated.co @templatedco
	Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
<html>
	<head>
		<title>Açık Seçik Aşk Bandosu</title>
    <%= csrf_meta_tags %>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
    <%= stylesheet_link_tag    'main', media: 'all', 'data-turbolinks-track': 'reload' %>
		<link rel="icon" href="images/logo.jpg">

	</head>
	<body>


		<!-- Header -->
    <header id="header">


      <div class="logo"><!–– foto gelicek --><a><%= link_to 'byStudio',root_path %></a></div>
      <a href="#menu"><span>Menu</span></a>
    </header>

		<!-- Nav -->
    <%= render partial: 'partials/navbar' %>

		<!-- Banner -->
		<!--
			Note: To show a background image, set the "data-bg" attribute below
			to the full filename of your image. This is used in each section to set
			the background image.
		-->
			<section id="banner" class="bg-img" data-bg="<%=image_path('kapak1.jpg') %>">
				<div class="inner">
					<header>
						<h1>Açık Seçik Aşk Bandosu</h1>
					</header>
				</div>
				<a href="#one" class="more">Learn More</a>
			</section>

		<!-- One -->
			<section id="one" class="wrapper post bg-img" data-bg="<%=image_path('guitars.jpg') %>">
				<div class="inner" >
					<article class="box">
						<header >
							<h2 style="font-family: cursive; text-transform: lowercase;">açık seçik aşk şarkılar</h2>
							<p style="font-family: cursive; text-transform: lowercase;" >March 2014</p>
						</header>
						<div class="content">
							<p>Epey bir Açık Hem de Seçik bir Aşkın Bandosu</p>
						</div>
						<footer>
							<a href="../../../../../WebstormProjects/asab/seyler.html" class="button alt" style="text-transform: lowercase">şeyler</a>
						</footer>
					</article>
				</div>
				<a href="#two" class="more" >şeyler</a>
			</section>

		<!-- Two -->
			<section id="two" class="wrapper post bg-img" data-bg=<%=image_path('akor.jpg') %>>
				<div class="inner">
					<article class="box">
						<header>
              <h2 style="font-family: cursive; text-transform: lowercase;">açık seçik aşk akorları</h2>
              <p style="font-family: cursive; text-transform: lowercase;" >March 2014</p>
	ea			</header>
						<div class="content">
							<p>Scelerisque enim mi curae erat ultricies lobortis donec velit in per cum consectetur purus a enim platea vestibulum lacinia et elit ante scelerisque vestibulum. At urna condimentum sed vulputate a duis in senectus ullamcorper lacus cubilia consectetur odio proin sociosqu a parturient nam ac blandit praesent aptent. Eros dignissim mus mauris a natoque ad suspendisse nulla a urna in tincidunt tristique enim arcu litora scelerisque eros suspendisse.</p>
						</div>
						<footer>
							<a href="generic.html" class="button alt" style="text-transform: lowercase">şeyler</a>
						</footer>
					</article>
				</div>
				<a href="#three" class="more">Learn More</a>
			</section>

		<!-- Three -->
			<section id="three" class="wrapper post bg-img" data-bg="banner4.jpg">
				<div class="inner">
					<article class="box">
						<header>
							<h2>Varius a cursus aliquet</h2>
							<p>11.11.2016</p>
						</header>
						<div class="content">
							<p>Scelerisque enim mi curae erat ultricies lobortis donec velit in per cum consectetur purus a enim platea vestibulum lacinia et elit ante scelerisque vestibulum. At urna condimentum sed vulputate a duis in senectus ullamcorper lacus cubilia consectetur odio proin sociosqu a parturient nam ac blandit praesent aptent. Eros dignissim mus mauris a natoque ad suspendisse nulla a urna in tincidunt tristique enim arcu litora scelerisque eros suspendisse.</p>
						</div>
						<footer>
							<a href="generic.html" class="button alt">Learn More</a>
						</footer>
					</article>
				</div>
				<a href="#four" class="more">Learn More</a>
			</section>

		<!-- Four -->
			<section id="four" class="wrapper post bg-img" data-bg="banner3.jpg">
				<div class="inner">
					<article class="box">
						<header>
							<h2>Zeytinli Fest</h2>
							<p>24.08.2014</p>
						</header>
						<div class="content">
							<p>Scelerisque enim mi curae erat ultricies lobortis donec velit in per cum consectetur purus a enim platea vestibulum lacinia et elit ante scelerisque vestibulum. At urna condimentum sed vulputate a duis in senectus ullamcorper lacus cubilia consectetur odio proin sociosqu a parturient nam ac blandit praesent aptent. Eros dignissim mus mauris a natoque ad suspendisse nulla a urna in tincidunt tristique enim arcu litora scelerisque eros suspendisse.</p>
						</div>
						<footer>
							<a href="generic.html" class="button alt">Learn More</a>
						</footer>
					</article>
				</div>
			</section>

		<!-- Footer -->
			<footer id="footer">
				<div class="inner">

					<h2>Contact Me</h2>

					<form action="#" method="post">

						<div class="field half first">
							<label for="name">Name</label>
							<input name="name" id="name" type="text" placeholder="Name">
						</div>
						<div class="field half">
							<label for="email">Email</label>
							<input name="email" id="email" type="email" placeholder="Email">
						</div>
						<div class="field">
							<label for="message">Message</label>
							<textarea name="message" id="message" rows="6" placeholder="Message"></textarea>
						</div>
						<ul class="actions">
							<li><input value="Send Message" class="button alt" type="submit"></li>
						</ul>
					</form>

					<ul class="icons">
						<li><a href="#" class="icon round fa-twitter"><span class="label">Twitter</span></a></li>
						<li><a href="#" class="icon round fa-facebook"><span class="label">Facebook</span></a></li>
						<li><a href="#" class="icon round fa-instagram"><span class="label">Instagram</span></a></li>
					</ul>

					ntitled. Design: TEMPLATED. Images: <a href="https://unsplash.com">Unsplash</a>.
					</div>

				</div>
			</footer>

		<!-- Scripts -->
      <%= javascript_include_tag 'jquery.min', 'data-turbolinks-track': 'reload' %>

      <%= javascript_include_tag 'jquery.scrollex.min', 'data-turbolinks-track': 'reload' %>

      <%= javascript_include_tag 'skel.min', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'util', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'main', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'jquery.scrolly.min', 'data-turbolinks-track': 'reload' %>




  </body>
</html>